<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HPDA0452" name="SNL.SNLTestCase.BoardTest" tests="7" failures="0" timestamp="02 Jul 2018 06:10:26 GMT" time="0.118" errors="1">
  <testcase name="nameRedundancy_test" time="0.008" classname="SNL.SNLTestCase.BoardTest"/>
  <testcase name="position_test" time="0.011" classname="SNL.SNLTestCase.BoardTest"/>
  <testcase name="registerPlayer_test" time="0.007" classname="SNL.SNLTestCase.BoardTest"/>
  <testcase name="maxPlayer_test" time="0.056" classname="SNL.SNLTestCase.BoardTest"/>
  <testcase name="turn_test" time="0.008" classname="SNL.SNLTestCase.BoardTest"/>
  <testcase name="playerNotExist_test" time="0.019" classname="SNL.SNLTestCase.BoardTest">
    <error type="org.json.JSONException" message="JSONObject[&quot;uuid&quot;] not a string.">
      <![CDATA[org.json.JSONException: JSONObject["uuid"] not a string.
at org.json.JSONObject.getString(JSONObject.java:721)
at SNL.SNLTestCase.Board.deletePlayer(Board.java:66)
at SNL.SNLTestCase.BoardTest.playerNotExist_test(BoardTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- playerNotExist_test -->
  <testcase name="validRoll_test" time="0.009" classname="SNL.SNLTestCase.BoardTest"/>
</testsuite> <!-- SNL.SNLTestCase.BoardTest -->
